[phases.setup]
nixPkgs = ['ffmpeg', 'libsndfile']

[phases.install]
cmds = ['pip install --upgrade pip', 'pip install -r requirements.txt']

[phases.build]
cmds = ['python download_models.py']

[start]
cmd = 'python app.py'
